[project]
name = "llm-genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tonu1990", email = "58003234+tonu1990@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
llm-genai = "llm_genai:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
